from pygoogle import pygoogle
import webbrowser
import time

def firstHit(query):
	time.sleep(1)
	searchResults = pygoogle(query)
	searchResults.pages = 1
	url = searchResults.get_urls()[0]
	webbrowser.open_new(url)

colleges = ["Abilene Christian University",
"Agnes Scott College",
"Albion College",
"Albright College",
"Allegheny College",
"Alvernia College",
"American University",
"Amherst College",
"Arcadia University",
"Ashland University",
"Augsburg College",
"Augustana College",
"Augustana College",
"Austin College",
"Ave Maria University",
"Baldwin-Wallace University",
"Bard College",
"Baylor University",
"Belmont University",
"Beloit College",
"Berklee College of Music",
"Berry College",
"Birmingham-Southern College",
"Boston University",
"Bradley University",
"Brandeis University",
"Bridgewater College",
"Buena Vista University",
"Butler University",
"California Institute of Technology",
"California Lutheran University",
"Canisius College",
"Capital University",
"Carleton College",
"Carnegie Mellon University",
"Carson-Newman College",
"Case Western Reserve University",
"Catawba College",
"Catholic University of America",
"Centenary College",
"Centenary College of Louisiana",
"Central College",
"Centre College",
"Chaminade University of Honolulu",
"Chapman University",
"Charleston Southern University",
"Chatham University",
"Claflin University",
"Claremont McKenna College",
"Clark Atlanta University",
"Clark University",
"Clarke University",
"Coe College",
"College of Idaho",
"College of Wooster",
"Colorado College",
"Columbia College",
"Concordia College",
"Concordia University",
"Concordia University",
"Concordia University",
"Concordia University Texas",
"Converse College",
"Cornell College",
"Covenant College",
"Creighton University",
"Culver-Stockton College",
"Daemen College",
"Dallas Baptist University",
"Denison University",
"DePauw University",
"Dickinson College",
"Dillard University",
"Doane College",
"Dordt College",
"Drew University",
"Drexel University",
"Drury University",
"Duke University",
"Earlham College",
"Eastern Mennonite University",
"Elmhurst College",
"Elmira College",
"Emory University",
"Fairfield University",
"Faulkner University",
"Franklin & Marshall College",
"Franklin College",
"Franklin Pierce University",
"Furman University",
"George Fox University",
"George Washington University",
"Gettysburg College",
"Gordon College",
"Goucher College",
"Graceland University",
"Greensboro College",
"Grinnell College",
"Grove City College",
"Guilford College",
"Gustavus Adolphus College",
"Hamline University",
"Hampden-Sydney College",
"Hampshire College",
"Hannibal-LaGrange College",
"Hardin-Simmons University",
"Hartwick College",
"Harvey Mudd College",
"Hendrix College",
"Hiram College",
"Hobart & William Smith Colleges",
"Hollins University",
"Hope College",
"Illinois Institute of Technology",
"Illinois Wesleyan University",
"Immaculata University",
"Ithaca College",
"Jacksonville University",
"John Brown University",
"John Carroll University",
"Johns Hopkins University",
"Juniata College",
"Kalamazoo College",
"Kenyon College",
"Keystone College",
"Knox College",
"La Salle University",
"LaGrange College",
"Lake Forest College",
"Lakeland College",
"Lawrence University",
"Lenoir-Rhyne University",
"Lewis & Clark College",
"Linfield College",
"Loras College",
"Loyola University in Maryland",
"Lubbock Christian University",
"Luther College",
"Lyon College",
"Macalester College",
"Marist College",
"Mary Baldwin College",
"Maryville University of Saint Louis",
"Marywood University",
"McDaniel College",
"Medaille College",
"Mercer University",
"Methodist University",
"Middlebury College",
"Mills College",
"MIT",
"Monmouth College",
"Moravian College",
"Mount Holyoke College",
"Mount St. Mary's College",
"Mount St. Mary's University",
"Mount Vernon Nazarene University",
"Muhlenberg College",
"Muskingum University",
"Nazareth College",
"Niagara University",
"North Central College",
"Northwest Nazarene University",
"Northwestern College",
"Notre Dame of Maryland University",
"Oberlin College",
"Occidental College",
"Oglethorpe University",
"Ohio Wesleyan University",
"Oklahoma Christian University",
"Olivet Nazarene University",
"Pace University",
"Pacific Lutheran University",
"Pacific University",
"Pepperdine University",
"Pitzer College",
"Point Loma Nazarene University",
"Pomona College",
"Presbyterian College",
"Princeton University",
"Randolph College",
"Reed College",
"Regis University",
"Rensselaer Polytechnic Institute",
"Rhodes College",
"Rice University",
"Rider University",
"Ripon College",
"Roberts Wesleyan College",
"Rochester Institute of Technology",
"Rockhurst University",
"Roger Williams University",
"Rollins College",
"Rose-Hulman Institute of Technology",
"Saint Francis University",
"Saint Joseph's College",
"Saint Leo University",
"Saint Louis University",
"Saint Mary's College",
"Saint Mary's College of California",
"Saint Michael's College",
"Saint Xavier University",
"Salem College",
"Samford University",
"Schreiner University",
"Seattle Pacific University",
"Sewanee: University of the South",
"Shenandoah University",
"Simpson College",
"Skidmore College",
"Smith College",
"Southern Methodist University",
"Southern Nazarene University",
"Southwestern University",
"Spelman College",
"Springfield College",
"St. Edward's University",
"St. Mary's University of San Antonio",
"St. Olaf College",
"Stanford University",
"Stephens College",
"Stetson University",
"Stevens Institute of Technology",
"Susquehanna University",
"Sweet Briar College",
"Syracuse University",
"Texas Christian University",
"Thiel College",
"Tiffin University",
"Transylvania University",
"Trevecca Nazarene University",
"Trinity College",
"Trinity University",
"Tulane University",
"University of Chicago",
"University of Dallas",
"University of Dayton",
"University of Evansville",
"University of LaVerne",
"University of Mary Hardin-Baylor",
"University of Miami",
"University of Mobile",
"University of Notre Dame",
"University of Redlands",
"University of Richmond",
"University of Rochester",
"University of San Diego",
"University of St. Thomas",
"University of the Pacific",
"University of Tulsa",
"Ursinus College",
"Valparaiso University",
"Vanderbilt University",
"Vassar College",
"Virginia Wesleyan College",
"Wabash College",
"Wagner College",
"Wake Forest University",
"Wartburg College",
"Washington & Jefferson College",
"Washington University in St. Louis",
"Waynesburg University",
"Webster University",
"Wellesley College",
"Wells College",
"Wesleyan College",
"Wesleyan University",
"West Virginia Wesleyan College",
"Westminster College",
"Westminster College",
"Westmont College",
"Wheaton College",
"Wheeling Jesuit University",
"Whittier College",
"Whitworth University",
"Willamette University",
"Wittenberg University",
"Wofford College",
"Xavier University",
"York College of Pennsylvania"]
i = 0
for college in colleges:
	print college
	firstHit(college + "US News and World Report")
	firstHit(college)
	i = i + 1
	if i == 5:
		raw_input("Press Enter to continue...")
